services:
  backend:
    build:
      dockerfile: backend.Dockerfile
    ports:
     - 8000:8000
    depends_on:
     - redis
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
  redis:
    image: redis
